### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by Tony-il-Capo** [SimpleMobileTools/Simple-Music-Player#20]
An user defined equalizer would be great. 
Default ones are useless to me.
Would be a feature you could add?

Thanks for your time.

**Comment by tibbi** [comment]
The music player is still missing a lot of features, this might come in the future too.

**Comment by GuitarBilly** [comment]
hello @tibbi 
i see nowadays there is an equalizer in the settings with many presets. 
However, changing equalizer presets does not seem to make any difference in sound.

1. is equalizer supposed to work?
2. can you share the settings for the various presets?

Simple Music Player v4.1.1

**Comment by tibbi** [comment]
1. it is supposed to work
2. I cannot since Im not creating them manually, I ask the system for them and just list the results

**Comment by takeshi4126** [comment]
Hello @tibbi, first of all thanks for the great app and made it open source. 

Regarding question 1 from @GuitarBilly, shouldn't the setupEqualizer method in the SettingsActivity.kt send the SET_EQUALIZER intent, in order to reflect the equalizer preference in the MusicService? Although the MusicService has the routine to handle the intent, I couldn't find the caller of it anywhere...

**Comment by tibbi** [comment]
not sure, maybe. Ill retest it when Ill be working on the app.

**Comment by puppykickr** [comment]
I am also having this issue.
The EQ makes no difference on any setting.

ZTE 558VL android 7.1.1

**Comment by tibbi** [comment]
a more advanced equalizer has been added already, it will receive further improvements in the future
