### ISSUE TITLE
If the phone rings and the playback pauses, it doesnt resume after pause automatically

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Music-Player#340]
Can be any audio Ducking effect, doesnt have to be a phone ringing

**Comment by qwertyfinger** [comment]
## Reason
I can reproduce this when the focus is lost for at least 10-20 seconds or when opening other apps that consume memory during the focus loss.
The reason is that we call `stopForeground` on focus loss, and our Service can be easily stopped by the OS whenever it wants to.

## Possible solutions
- Using `START_STICKY` doesn't fix this as our Service does not get recreated after being destroyed for some reason.
- One common approach that I saw used in apps like YouTube and Poweramp is to never call `stopForeground` so the notification is not dismissable and Service is not killed. Instead, they show an "X" button in the notification that allows to explicitly kill the app.
- Spotify does not use that – it allows you to dismiss the notification, and even after that, it will resume playback on focus gain. I'm not sure how exactly they do that, maybe with some BroadcastReceivers. But this behavior seems too invasive, to be honest. Because even if you think you killed the app, it will still come back.
- YouTube Music just dies silently :)

## Proposed solution
I was able to tweak the first solution to call `stopForeground` when the playback is stopped for any reason except the focus loss. This way, our Service doesn't get killed and always restarts when we gain back focus.
The only problem is that if we lose focus and don't receive a focus gain event (for example, after the user played and stopped a YouTube video), our notification will be non-dismissable. And the only way to make it dismissable is to hit "Play" and then "Pause".
So, for a better UX, we would probably still need to display the "X" button, so the user can easily kill our process if they want to. We can show it only in this specific case and display the usual notification layout in all others.

### "X" button examples
- YouTube only shows the "X" button in expanded state: ![YouTube expanded state](https://user-images.githubusercontent.com/7561414/131241940-ae23d189-6d86-4031-b692-027168b3974a.png)
- Poweramp collapsed state: ![Poweramp collapsed state](https://user-images.githubusercontent.com/7561414/131241942-4f5881ab-d474-4a73-918a-3aff115650e6.png)
- Poweramp expanded state: ![Poweramp expanded state](https://user-images.githubusercontent.com/7561414/131241943-ce6210b3-25cc-41b8-994c-c1bdf704f87b.png)

**Comment by qwertyfinger** [comment]
You can check out the current fix that doesn't have the "X" button here: https://github.com/qwertyfinger/Simple-Music-Player/tree/fix-audio-focus.

**Comment by tibbi** [comment]
I cannot actually reproduce the issue itself now as it resumes just fine after some call. So Ill accept this fix for now and see if it solves anything, or people will still report it. Thanks

**Comment by tibbi** [comment]
so create a pull request with that change from your repo, I tested it and it looks like it didnt break anything :)

**Comment by qwertyfinger** [comment]
You can try to reproduce the issue by creating a Google Meet or some other video call, join it by yourself, and then minimize it and open and scroll through a bunch of other heavy apps, do it for ~20 seconds. That should definitely be enough for the OS to decide to kill the process

**Comment by tibbi** [comment]
will be added in 5.7.1
