### ISSUE TITLE
Notification banner cannot be dismissed anymore 

### ISSUE THREAD

**Issue by serkonda7** [SimpleMobileTools/Simple-Music-Player#427]
With the recent version, the notification banner cannot be dismissed anymore even if the app is closed and no song is playing.

**Comment by tibbi** [comment]
but was it playing after launching? Any steps for reproducing the issue?

**Comment by serkonda7** [comment]
1. open the app
2. completely close the app so it doesn't show up in `recent apps` anymore
3. Try to swipe the notification banner away

Expected:
Banner is not shown

Actual Result:
Banner only hides after force stop

**Comment by Phantom21x** [comment]
I'm having the same problem, the banner only goes away after I force-stop the app. 

I came across another issue earlier today after I restarted my phone. I didn't launch the app but the banner was in my notification bar which was weird because the app was not open/running or anything before I restarted my phone.

**Comment by serkonda7** [comment]
Thanks a lot :)

**Comment by tibbi** [comment]
recheck if it wont break in 5.14.2 once released please

**Comment by serkonda7** [comment]
Works, thanks
