### ISSUE TITLE
Option to add song to queue when tapping it

### ISSUE THREAD

**Issue by diggy128** [SimpleMobileTools/Simple-Music-Player#431]
When having a few songs on a queue and you simple tap on one, the queue is replaced with current folder's song and starts playing the selected song.

It would be nice to be able to simply add songs to queue by tapping them on the folder view without removing the selected queue (long tapping is possible but is cumbersome if you want to mash up a quick selection)

**Comment by tibbi** [comment]
you can select the wanted ones and using Menu -> Add to queue. I dont plan implementing that on click.

**Comment by diggy128** [comment]
Ok. But the default behavior is to replace the queue when tapping a song. Is this the desired behavior?

**Comment by tibbi** [comment]
sure

**Comment by pasckosky** [comment]
Is it possible to be able to choose between "replace", "add to queue" and "prevent accidental taps" ?

I say so because sometimes due to accidental tap (for example when you just want to scroll, but you move your finger too little and ui get it as a tap) the queue is replaced without intentions and then you have to rebuild the queue again.

Then the default can be "replace" as it currently is.

Just an idea.
