### ISSUE TITLE
Import playlist failed 

### ISSUE THREAD

**Issue by Offerel** [SimpleMobileTools/Simple-Music-Player#502]
I have saved a playlist in m3u format with relative paths to the songs. If I import this playlist, the import fails. The playlist is exported and created by a application called "Strawberry" under Arch Linux.

Is there some other playlist format with relative paths, which I should use instead?

**Comment by tibbi** [comment]
what do you mean by relative paths? Can you tell a sample?

**Comment by mgolden356** [comment]
> I have saved a playlist in m3u format with relative paths to the songs. If I import this playlist, the import fails. The playlist is exported and created by a application called "Strawberry" under Arch Linux.
> 
> Is there some other playlist format with relative paths, which I should use instead?

I was having this problem, and after comparing the files of what the other app Phonograph Plus, and this app, for the m3u file exports, I found that I needed to add 
> #EXTM3U
at the top line, for this app to recognize the other playlist.

It works the reverse way onto phonograph plus, so I bet the fix is to let this app recognize playlists without
> #EXTM3U
as the top line.

I'm not sure at all this will fix the relative patching stuff, but maybe this will? Good luck.

**Comment by mgolden356** [comment]
This might not help, but try adding

#EXTM3U

At the top of the m3u file if not already there

**Comment by Offerel** [comment]
That's already there. Currently it's a textfile with the following content:
```
#EXTM3U
Protonica/Assorted Waves 10/01 - Assorted Waves 10.mp3
Various/Birthday Mix/01 - Birthday Mix Part 2.m4a
Bonobo/Bonobos DJ-Set at Boiler Room/01 - @ Boiler Room NYC, Januar 2018.mp3
Die Vogelperspektive/Brise Podcast/01 - Brise Podcast.mp3
```

The playlist is saved in `/storage/emulated/0/Music`. The songs in the same folder as mentioned in the m3u file.

I have tested other players, and all of them can use the list without issues. I have not tested Phonograph, only Vinyl player, which seems to be based on Phonograph. There it works.

**Comment by tibbi** [comment]
we dont plan adding support for such relative paths, it might not work due to system restrictions
