### ISSUE TITLE
App crash on start

### ISSUE THREAD

**Issue by CodeCubeNeo** [SimpleMobileTools/Simple-Music-Player#566]
Error message is something java.NullPointerException: Album shouldnt be null (See screenshot)
![Screenshot_20230723_100832](https://github.com/SimpleMobileTools/Simple-Music-Player/assets/61159092/3ecc24c1-b5f1-49d1-9f8e-aae6ad3b071a)

**Comment by tibbi** [comment]
what app version are you using?

**Comment by CodeCubeNeo** [comment]
Guess. Well if I make such an issue, you can assume I am using the latest. Meaning 5.17.0.

**Comment by naveensingh** [comment]
Hey!
Are you seeing this toast at _every_ start? If I send an APK, will you be able to check if it fixes your issue? If not, can you provide any info regarding the kind of audio files you have (e.g. source of file)? 

Also, are you running some custom ROM or stock Android?

(I'm asking this because I tested audio files without album metadata on Android 9 and no error toasts were shown, they are properly displayed as unknown albums).

**Comment by CodeCubeNeo** [comment]
Yes. It flashes at every start, then crashes a second later. Stock Android 9 pn Huawei Mate 9. Also yes, you can send me an apk to try.

**Comment by naveensingh** [comment]
Okay, there were some new changes in 5.17.0 to improve file scanning but it looks like that has led to some device-specific crashes. Here are two test APKs:
Version 1: https://github.com/naveensingh/Simple-Music-Player/releases/download/avoid_null_albums/music-player-debug_v1.apk
Version 2: https://github.com/naveensingh/Simple-Music-Player/releases/download/avoid_null_albums/music-player-debug_v2.apk

(Both APKs were compiled from https://github.com/SimpleMobileTools/Simple-Music-Player/pull/569)

Please test version 1 and if it doesn't fix your issue, try version 2.

**Comment by CodeCubeNeo** [comment]
Version 1 works fine.

**Comment by CodeCubeNeo** [comment]
Version 2 also works.

**Comment by naveensingh** [comment]
okay, thanks, it'll be released soon.

**Comment by tibbi** [comment]
going to update the app, thanks for the feedback
